import { IContentTypes } from '../model/contentType.model';

export const contentTypes: IContentTypes[] = [
  {
    type: 'article',
    description:
      'Escreva um artigo completo e estruturado com introdução, desenvolvimento e conclusão.',
    tone: 'Jornalístico e informativo.',
    audience: 'Leitores gerais interessados em tecnologia e negócios.',
    structure: '<h2> para subtítulos, listas quando útil, foco em clareza.',
    goal: 'Informar e educar, mantendo fluidez e SEO natural.',
  },
  {
    type: 'social',
    description: 'Crie um texto curto (até 280 caracteres) para redes sociais.',
    tone: 'Envolvente, direto e humano.',
    audience: 'Usuários de Twitter/X ou LinkedIn.',
    structure: 'Frase de impacto + resumo curto. Não incluir hashtags automáticas.',
    goal: 'Gerar engajamento rápido.',
  },
  {
    type: 'news_summary',
    description: 'Compile resumos dos materiais brutos em formato de boletim de notícias.',
    tone: 'Neutro e objetivo.',
    structure: "Seções 'Notícia 1', 'Notícia 2', etc.",
    audience: 'Leitores que desejam atualização rápida.',
    goal: 'Consolidar informações recentes em um artigo coeso.',
  },
  {
    type: 'blog',
    description: 'Crie um post narrativo e analítico (800–1000 palavras).',
    tone: 'Editorial e fluido.',
    structure: 'História envolvente, transições suaves e subtítulos claros.',
    goal: 'Entreter e informar com profundidade.',
  },
  {
    type: 'newsletter',
    description: 'Monte um texto formatado para e-mails, com seções curtas e chamadas para ação.',
    structure: "'Destaques da Semana', 'Atualizações sobre [Tema]'.",
    tone: 'Conversacional e informativo.',
    goal: 'Engajar leitores recorrentes e aumentar retenção.',
  },
  {
    type: 'thread',
    description: 'Crie uma sequência de 3 a 5 posts curtos (máx. 280 caracteres cada).',
    structure: 'Numere implicitamente os posts.',
    tone: 'Didático e fluido.',
    audience: 'Usuários de Twitter/X.',
    goal: 'Explicar um conceito ou tendência passo a passo.',
  },
  {
    type: 'listicle',
    description: 'Escreva um artigo no formato de lista numerada.',
    structure: "'10 fatos sobre [Tema]'.",
    tone: 'Dinâmico, direto e informativo.',
    goal: 'Facilitar leitura escaneável e leve.',
  },
  {
    type: 'opinion',
    description: 'Redija um artigo de opinião.',
    tone: 'Persuasivo, crítico e argumentativo.',
    structure: 'Introdução da tese, defesa e conclusão reflexiva.',
    goal: 'Expor um ponto de vista fundamentado.',
  },
  {
    type: 'faq',
    description: 'Crie um artigo de perguntas e respostas.',
    structure: "'Pergunta: ...', 'Resposta: ...'.",
    audience: 'Leitores que buscam esclarecimento rápido.',
    goal: 'Tornar o tema acessível e prático.',
  },
  {
    type: 'infographic',
    description: 'Produza um texto descritivo para infográficos.',
    structure: 'Bullet points curtos, dados e fatos diretos.',
    goal: 'Servir de base textual para design visual.',
  },
  {
    type: 'tutorial',
    description: 'Monte um guia passo a passo.',
    structure: 'Numerada (1, 2, 3...) e clara.',
    audience: 'Pessoas buscando aprender algo prático.',
    goal: 'Ensinar de forma simples e objetiva.',
  },
  {
    type: 'review',
    description: 'Escreva uma análise crítica de produto, evento ou conceito.',
    structure: 'Introdução, prós, contras e conclusão.',
    tone: 'Neutro, comparativo e técnico.',
    goal: 'Ajudar na tomada de decisão.',
  },
  {
    type: 'whitepaper',
    description: 'Crie um documento técnico detalhado e analítico (1000+ palavras).',
    tone: 'Formal, profundo e baseado em dados.',
    structure: 'Seções técnicas, análises, conclusões.',
    goal: 'Informar especialistas e decisores.',
  },
];
